<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.4"/>
<PackageReference Include="AutoMapper" Version="12.0.1"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DocumentService.Application\DocumentService.Application.csproj" />
      <ProjectReference Include="..\DocumentService.Contracts\DocumentService.Contracts.csproj" />
      <ProjectReference Include="..\DocumentService.Data\DocumentService.Data.csproj" />
      <ProjectReference Include="..\DocumentService.Infrastructure\DocumentService.Infrastructure.csproj" />
    </ItemGroup>

</Project>
