// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherMinimal;

#nullable disable

namespace WeatherMinimal.Migrations
{
    [DbContext(typeof(WeatherContext))]
    partial class WeatherContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CityWeatherResultWeather", b =>
                {
                    b.Property<int>("Resultsid")
                        .HasColumnType("int");

                    b.Property<Guid>("weatherIdKey")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Resultsid", "weatherIdKey");

                    b.HasIndex("weatherIdKey");

                    b.ToTable("CityWeatherResultWeather");
                });

            modelBuilder.Entity("WeatherMinimal.CityWeatherResult", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("base")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("cloudsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("cod")
                        .HasColumnType("int");

                    b.Property<Guid>("coordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("dt")
                        .HasColumnType("int");

                    b.Property<Guid>("mainIdKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("rainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("sysId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("timezone")
                        .HasColumnType("int");

                    b.Property<int>("visibility")
                        .HasColumnType("int");

                    b.Property<Guid>("windId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.HasIndex("cloudsId");

                    b.HasIndex("coordId");

                    b.HasIndex("mainIdKey");

                    b.HasIndex("rainId");

                    b.HasIndex("sysId");

                    b.HasIndex("windId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("WeatherMinimal.Clouds", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("all")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clouds");
                });

            modelBuilder.Entity("WeatherMinimal.Coord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("lat")
                        .HasColumnType("float");

                    b.Property<double>("lon")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Coord");
                });

            modelBuilder.Entity("WeatherMinimal.Main", b =>
                {
                    b.Property<Guid>("IdKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("feels_like")
                        .HasColumnType("float");

                    b.Property<int>("grnd_level")
                        .HasColumnType("int");

                    b.Property<int>("humidity")
                        .HasColumnType("int");

                    b.Property<int>("pressure")
                        .HasColumnType("int");

                    b.Property<int>("sea_level")
                        .HasColumnType("int");

                    b.Property<double>("temp")
                        .HasColumnType("float");

                    b.Property<double>("temp_max")
                        .HasColumnType("float");

                    b.Property<double>("temp_min")
                        .HasColumnType("float");

                    b.HasKey("IdKey");

                    b.ToTable("Main");
                });

            modelBuilder.Entity("WeatherMinimal.Rain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("_h")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Rain");
                });

            modelBuilder.Entity("WeatherMinimal.Sys", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sunrise")
                        .HasColumnType("int");

                    b.Property<int>("sunset")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sys");
                });

            modelBuilder.Entity("WeatherMinimal.Weather", b =>
                {
                    b.Property<Guid>("IdKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("main")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKey");

                    b.ToTable("Weather");
                });

            modelBuilder.Entity("WeatherMinimal.Wind", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("deg")
                        .HasColumnType("int");

                    b.Property<double>("gust")
                        .HasColumnType("float");

                    b.Property<double>("speed")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Wind");
                });

            modelBuilder.Entity("CityWeatherResultWeather", b =>
                {
                    b.HasOne("WeatherMinimal.CityWeatherResult", null)
                        .WithMany()
                        .HasForeignKey("Resultsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeatherMinimal.Weather", null)
                        .WithMany()
                        .HasForeignKey("weatherIdKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeatherMinimal.CityWeatherResult", b =>
                {
                    b.HasOne("WeatherMinimal.Clouds", "clouds")
                        .WithMany("Results")
                        .HasForeignKey("cloudsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeatherMinimal.Coord", "coord")
                        .WithMany("Results")
                        .HasForeignKey("coordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeatherMinimal.Main", "main")
                        .WithMany("Results")
                        .HasForeignKey("mainIdKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeatherMinimal.Rain", "rain")
                        .WithMany("Results")
                        .HasForeignKey("rainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeatherMinimal.Sys", "sys")
                        .WithMany("Results")
                        .HasForeignKey("sysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeatherMinimal.Wind", "wind")
                        .WithMany("Results")
                        .HasForeignKey("windId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("clouds");

                    b.Navigation("coord");

                    b.Navigation("main");

                    b.Navigation("rain");

                    b.Navigation("sys");

                    b.Navigation("wind");
                });

            modelBuilder.Entity("WeatherMinimal.Clouds", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("WeatherMinimal.Coord", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("WeatherMinimal.Main", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("WeatherMinimal.Rain", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("WeatherMinimal.Sys", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("WeatherMinimal.Wind", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
