<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ContactService.Contracts\ContactService.Contracts.csproj" />
      <ProjectReference Include="..\ContactService.Data\ContactService.Data.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="../ContactService.Contracts/Protos/user.proto" GrpcServices="Client" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Grpc.Net.Client" Version="2.71.0"/>
        <PackageReference Include="Grpc.Tools" Version="2.72.0"/>
        <PackageReference Include="Grpc.Core" Version="2.46.6"/>
        <PackageReference Include="Google.Protobuf" Version="3.31.1"/>
      <PackageReference Include="AutoMapper" Version="12.0.1" />
    </ItemGroup>

</Project>
