<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="Repos\**" />
      <EmbeddedResource Remove="Repos\**" />
      <None Remove="Repos\**" />
    </ItemGroup>

</Project>
