<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AuditService.Application\AuditService.Application.csproj" />
      <ProjectReference Include="..\AuditService.Contracts\AuditService.Contracts.csproj" />
      <ProjectReference Include="..\AuditService.Data\AuditService.Data.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AspNetCore.HealthChecks.MongoDb" Version="6.0.1" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.7" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.7" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.7" />
      <PackageReference Include="RabbitMQ.Client" Version="7.1.2" />
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.7" />
    </ItemGroup>

</Project>
