apiVersion: v1
kind: Service
metadata:
  name: minio-console
spec:
  selector:
    app: minio-console
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-console
  template:
    metadata:
      labels:
        app: minio-console
    spec:
      containers:
        - name: minio-console
          image: quay.io/minio/console:v0.30.0
          command: ["/bin/console", "server"]
          ports:
            - containerPort: 9001
          env:
            - name: CONSOLE_MINIO_SERVER
              value: "http://minio:9000"
            - name: CONSOLE_MINIO_USER
              value: "minioadmin"
            - name: CONSOLE_MINIO_PASSWORD
              value: "minioadmin"
