apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactionservice
  namespace: banktask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactionservice
  template:
    metadata:
      labels:
        app: transactionservice
    spec:
      containers:
        - name: transactionservice
          image: profbat018/banktask-transactionservice:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
---
apiVersion: v1
kind: Service
metadata:
  name: transactionservice
  namespace: banktask
spec:
  selector:
    app: transactionservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
